version = 0.1

[default.deploy.parameters]
stack_name = "firearm-api-dev"
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "firearm-api-dev"
region = "ap-northeast-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "ApiStageName=Dev",
    "VpcSecurityGroupIds=sg-002293484aef9c5f7",
    "VpcSubnetIds=subnet-0c01c03a37771dbc2,subnet-07b0370ae1e14db0f,subnet-077e9f5dc80174528"
]

[prod.deploy.parameters]
stack_name = "firearm-api-prod"
resolve_s3 = true
s3_prefix = "firearm-api-prod"
region = "ap-northeast-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "ApiStageName=Prod",
    "VpcSecurityGroupIds=sg-002293484aef9c5f7",
    "VpcSubnetIds=subnet-0c01c03a37771dbc2,subnet-07b0370ae1e14db0f,subnet-077e9f5dc80174528"
]

