# .github/workflows/main.yml

name: Deploy Firearm API to Production

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run Pytest
      env:
        DB_SERVER: "localhost"
        DB_NAME: "testdb"
        DB_USER: "testuser"
        DB_PORT: "5432"
        DB_PASSWORD: "testpassword"
        SECRET_KEY: "testsecret"
      run: pytest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Deploy with SAM
      run: |
        # This command builds the Docker image and prepares the deployment artifacts
        sam build --use-container

        # Set your VPC configuration
        VPC_SUBNET_IDS="subnet-0c01c03a37771dbc2,subnet-07b0370ae1e14db0f,subnet-077e9f5dc80174528"
        VPC_SECURITY_GROUP_ID="sg-002293484aef9c5f7"
        
        # This command now pushes the built image to ECR and deploys
        sam deploy --stack-name firearm-api-prod \
                   --image-repository ${{ steps.login-ecr.outputs.registry }}/firearm-api-repo \
                   --no-confirm-changeset \
                   --no-fail-on-empty-changeset \
                   --capabilities CAPABILITY_IAM \
                   --parameter-overrides VpcSubnetIds=$VPC_SUBNET_IDS VpcSecurityGroupIds=$VPC_SECURITY_GROUP_ID